# 00: Short and Incomplete Introduction to Python (and some MATLAB)

### Notebook accompanying  the [Scientific Computing Lecture HS 2017](http://informatik.unibas.ch/hs2017/hauptvorlesung-scientific-computing/)
#### Tutorial by [Sebastian Mathias Keller](http://bmda.cs.unibas.ch/)
#### University of Basel [Institute for Mathematics and Computer Science](http://informatik.unibas.ch/)

## Table of contents

1. [Organization of the Tutorial](#Organization-of-the-Tutorial)

2. [Python and Required libraries](#Python-and-Required-libraries)

3. [A Python Program with Vectorization and Plotting](#A Python Program with Vectorization and Plotting)

4. [Basic Constructions](#Basic-Constructions)

    - [If Tests, Colon and Indentation](#If-Tests,-Colon-and-Indentation)

    - [Functions](#Functions)

    - [For Loops](#For-Loops)
    
    - [While Loops](#While-Loops)

    - [Lists and Tuples - Alternatives to Arrays](#Lists-and-Tuples---Alternatives-to-Arrays)

    - [Reading from and Writing to Files](#Reading-from-and-Writing-to-Files)
    
5. [MATLAB commands in Python](#MATLAB-commands-in-Python)
6. [Linear Systems of Equations](#Linear-Systems-of-Equations)
7. [Not covered but relevant...](#Not-covered-but-relevant...)
8. [Further reading and references](#Further-reading-and-references)

 ## Organization of the Tutorial
 
 [[ go back to the top ]](#Table-of-contents)
 
- Tutorial based on Jupyter Notebooks
- Tutorial and Tutorial Exercises are connected (!)
- Tutorial is voluntary but a good exam preparation...
- Topics covered:
    - Linear Systems of Equations
    - Least squares problems
    - Linear Dimensionality Reduction and Eigenvalue Problems
    - Linear Programming
    - Optimization without Gradients
    - Dynamic Programming
- Tutorial: CLab U1.001, Thur 16:15-18:00 OR Fri 10:15-12:00
- Tutorial Materials: [ADAM](https://adam.unibas.ch)
- EXAM: Wednesday, 24 January 2018, 9-11 a.m., Room: U 101, Alte Universität

**This notebook is intended to be a useful resource. As such, if you see any glaring inaccuracies or if a critical
topic is missing, please feel free to point it out!**

## Python and Required libraries

[[ go back to the top ]](#Table-of-contents)

If you don't have Python on your computer, you can use the [Anaconda Python distribution](http://continuum.io/downloads) to install most of the Python packages you need. Anaconda provides a simple double-click installer for your convenience.

This notebook uses several Python packages that come standard with the Anaconda Python distribution. The primary libraries that we'll be using are:

* **NumPy**: Provides a fast numerical array structure and helper functions.

  `import numpy as np`
  
  
* **pandas**: Provides a DataFrame structure to store data in memory and work with it easily and efficiently.

  `import pandas as pd`
  
  
* **scikit-learn**: The essential Machine Learning package in Python.

  `from sklearn import x`


* **matplotlib**: Basic plotting library in Python; most other Python plotting libraries are built on top of it.

  `import matplotlib.pyplot as plt`
  
  


To make sure you have all of the packages you need, install them with `conda`:

    conda install numpy pandas scikit-learn matplotlib

`conda` may ask you to update some of them if you don't have the most recent version. Allow it to do so.

**Note:** I will not be providing support for people trying to run this notebook outside of the Anaconda Python distribution.

## A Python Program with Vectorization and Plotting

[[ go back to the top ]](#Table-of-contents)

In [1]:
print('Hello World')

Hello World


A ball is thrown up in the air and we have a formula for the vertical
position y of the ball. Say we are interested in y at every millisecond
for the first second of the flight. This requires repeating the calculation of
$y=v_0t-0.5gt^2$ one thousand times.

The value returned from `linspace` (being stored in `t` ) is an **array**, i.e., a collection of
numbers. When we start computing with this collection of numbers in the
arithmetic expression $y=v_0t-0.5gt^2$, the expression is calculated for every
number in `t`.

## Basic Constructions

[[ go back to the top ]](#Table-of-contents)

### If Tests, Colon and Indentation

[[ go back to the top ]](#Table-of-contents)

In [ ]:
# Moving in different directions...

import random

r = random.random()      # random number in [0,1)

x=0
y=0
d=1

if 0 <= r < 0.25:
    # move to ...?
    y = y + d
elif 0.25 <= r < 0.5:
    # move to ...?
    x = x + d
elif 0.5 <= r < 0.75:
    # move to ...?
    y = y - d
else:
    # move to ...?
    x = x - d

print("new coord:", x,y)

### Functions

[[ go back to the top ]](#Table-of-contents)

In [ ]:
# function definition in Python

### For Loops

[[ go back to the top ]](#Table-of-contents)

In [ ]:
from numpy import linspace
import matplotlib.pyplot as plt

v0 = 5                    # Initial velocity
g = 9.81                  # Acceleration of gravity
t = linspace(0, 1, 1000)  # 1000 points in time interval
y = v0*t - 0.5*g*t**2     # Generate all heights

# At this point, the array y with all the heights is ready.
# Now we need to find the largest value within y.

largest_height = y[0]          # Starting value for search
for i in range(1, 1000):
    if y[i] > largest_height:
        largest_height = y[i]
        
print("The largest height achieved was %f m" % (largest_height))

# We might also like to plot the path again just to compare
plt.plot(t,y)
plt.xlabel('Time (s)')
plt.ylabel('Height (m)')
plt.grid()
plt.show()

### While Loops

[[ go back to the top ]](#Table-of-contents)

In [ ]:
from numpy import linspace

v0 = 4.5                  # Initial velocity
g = 9.81                  # Acceleration of gravity
t = linspace(0, 1, 1000)  # 1000 points in time interval
y = v0*t - 0.5*g*t**2     # Generate all heights

# Find where the ball hits y=0
i = 0
while y[i] >= 0:
    i += 1

# Now, y[i-1]>0 and y[i]<0 so let’s take the middle point
# in time as the approximation for when the ball hits h=0
print("y=0 at", 0.5*(t[i-1] + t[i]))

# We plot the path again just for comparison
import matplotlib.pyplot as plt
plt.plot(t, y)
plt.plot(t, 0*t, 'g--')
plt.xlabel('Time (s)')
plt.ylabel('Height (m)')
plt.grid()
plt.show()

### Lists and Tuples - Alternatives to Arrays

[[ go back to the top ]](#Table-of-contents)

We have seen that a group of numbers may be stored in an array that we may treat
as a whole, or element by element. In Python, there is another way of organizing 
data that actually is much used, at least in non-numerical contexts, and that is
a construction called **list**.

**Note:** The `range()` function that we used above in our for loop actually returns a list.

In [ ]:
# A list may be created by simply writing, e.g.,


## Reading from and Writing to Files

[[ go back to the top ]](#Table-of-contents)

### Reading...
Input data for a program often come from files and the results of the computations
are often written to file. To illustrate basic file handling, we consider an example
where we read `x` and `y` coordinates from two columns in a file, apply a function `f`
to the `y` coordinates, and write the results to a new two-column data file.

In [ ]:
filename = 'tmp.dat'
infile = open(filename, 'r')  # Open file for reading
line = infile.readline()      # Read first line
# Read x and y coordinates from the file and store in lists
x = []
y = []
for line in infile:
    words = line.split()      # Split line into words
    x.append(float(words[0]))
    y.append(float(words[1]))
infile.close()
print("x_list:",x,"\ny_list:",y)

### Formatting numbers...

In [ ]:
import numpy as np


### Writing...

In [40]:
import numpy

# get data from file
filename = 'tmp.dat'
data = numpy.loadtxt(filename, comments='#')
x = data[:,0]
y = data[:,1]

# data manipulation
data[:,1] = numpy.log(y) # insert transformed y back in array

# file: open -- write -- close
filename = 'tmp_out.dat'
outfile = open(filename, 'wb') # open file for writing
outfile.write(b'# x and y coordinates\n')
numpy.savetxt(outfile, data, fmt='%10.5f')   # use exponential notation: %1.4e
                                             # use: delimiter=","
outfile.close()

## MATLAB commands in Python

[[ go back to the top ]](#Table-of-contents)

 **Quick reference** for switching from MATLAB to an open-source environment, such as Python, Scilab, Octave and Gnuplot, or R for numeric processing and data visualisation: [Cheatsheet: MATLAB vs Python](http://mathesaurus.sourceforge.net/matlab-python-xref.pdf)

## Linear Systems of Equations

[[ go back to the top ]](#Table-of-contents)

In [18]:
import numpy as np

A = np.array([[1,2,3,4, 2,1,2,3, 3,2,1,2, 4,3,2,1]])
A = A.reshape((4,4))
print(A)

b = np.array([[30, 22, 18, 20]])
b = b.T 
print(b)

# Create augmented matrix A_aug (corresponds to "A'" in lecture notes)
A_aug = np.concatenate((A, b, np.identity(4)), axis=1) 
print(A_aug)
rows, cols = A_aug.shape
print((rows,cols))

# Now we apply linear combinations of rows to receive the desired structure.
for i in range(rows):
    # Divide row i by the diagonal element. This will give a 1 on the diagonal.
    A_aug[i,:] = A_aug[i,:]/A_aug[i,i]
    
    # The next step is to substract row i from all other rows such that we receive the zeros in column i.
    for k in range(rows):
        if(k != i):
            A_aug[k,:] = A_aug[k,:] -A_aug[k,i] * A_aug[i,:]
            
x = np.array([A_aug[:,rows]]) 
x = x.T

print("Solution vector x:\n", x)

#print("\n\n--- Check ---\n")
#print("A * x == b? \n\n")
#Ax = A.dot(x)
#print("Ax:\n", Ax, "\n\nb:\n", b)

[[1 2 3 4]
 [2 1 2 3]
 [3 2 1 2]
 [4 3 2 1]]
[[30]
 [22]
 [18]
 [20]]
[[  1.   2.   3.   4.  30.   1.   0.   0.   0.]
 [  2.   1.   2.   3.  22.   0.   1.   0.   0.]
 [  3.   2.   1.   2.  18.   0.   0.   1.   0.]
 [  4.   3.   2.   1.  20.   0.   0.   0.   1.]]
(4, 9)


TypeError: unsupported format string passed to numpy.ndarray.__format__

### Ex.1

On the original problem: Interchange the first and the second column in A. Try your code...


### Ex.2

Try your code on $Ax=b$ with

$$
A = \begin{pmatrix}
 1 &  0 & -5\\
-6 &  2 &  9\\
 2 & -3 &  7
\end{pmatrix}
$$

and

$$
b = \begin{pmatrix}
1\\
3\\
2
\end{pmatrix}
$$

### Ex.3

On the problem from Ex2: Interchange the first and the second column in A. Try your code...

## Further reading and references

[[ go back to the top ]](#Table-of-contents)

Books I use for reference, inspiration and when designing exercise sheets or e.g. this Jupyter Notebook. Also a good idea if you're looking to dive deeper into a particular topic...

**Titus A. Beu: Introduction to numerical programming. A practical guide for scientists and engineers using Python and C/C++** This text introduces platform-independent numerical programming using Python and C/C++ and
appeals to advanced undergraduate and graduate students in natural sciences and engineering,
researchers involved in scientific computing, and engineers carrying out applicative calculations.

**Svein Linge and Hans Petter Langtangen: Programming for Computations - Python. A Gentle Introduction to Numerical Simulations with Python** This book presents computer programming as a key method for solving mathematical problems. There are two versions of the book, one for MATLAB and one for Python. The book was inspired by the Springer book TCSE 6: A Primer on Scientific Programming with Python (by Langtangen), but the style is more accessible and concise, in keeping with the needs of engineering students.

## Not covered but relevant...

[[ go back to the top ]](#Table-of-contents)

Sometimes there are details I would like to work out further or demonstrate during the tutorial but due to time limitations this is not always possible. So here is where I would usually point out things or ask questions that are important/interesting but I had to omit. These might simply be of general interest but could also emphasize a fact that would be useful to know e.g. for the upcoming exam...

>Nothing this week...