In [1]:
import numpy as np

A = np.array([[1.0, 0.0, -5.0], [-6.0, 2.0, 9.0], [2.0, -3.0, 2.0]])
print(A)

def lu(A):

    cols,rows = A.shape

    id_mat = np.zeros((cols,rows))
    pivot = np.identity(cols)

    print()

    k = -1
    for j in range(cols):
        max = np.argmax(abs(A[:,j]))

        if max != j & max !=k:
            k = max
            A[[j,max]] = A[[max,j]]
            id_mat[[j,max]] = id_mat[[max,j]]
            pivot[[j,max]] = pivot[[max,j]]

        for i in range(j,cols - 1):
            id_mat[i + 1, j] = A[i + 1, j] / A[j, j]
            A[i+1, :] = A[i+1, :] - (A[i+1, j] / A[j, j]) * A[j, :]

    np.fill_diagonal(id_mat,1)
    return id_mat,A,pivot

L,U,P = lu(A)
print(L)
print()
print(U)
print()
print(P)

[[ 1.  0. -5.]
 [-6.  2.  9.]
 [ 2. -3.  2.]]

[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-0.16666667 -0.14285714  1.        ]]

[[-6.          2.          9.        ]
 [ 0.         -2.33333333  5.        ]
 [ 0.          0.         -2.78571429]]

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]


In [3]:
import numpy as np

# P.A.x = L.U.x
#
# L.U.x = P.b       ForwardSubs --> U.x = y --> L.y = P.b
#                   BackWardSubs --> U.x = y
#
# y(i) = (b(i) - sum(A(i,j))/a(i,i)---> always 1

def forwardSubs(L, b, P):
    cols, rows = L.shape
    if P is not None:
        b = np.dot(P,b)
    y = np.zeros((cols, 1))
    for i in range(cols):
        s = 0
        for j in range(0,i):
            s = s + L[i,j] * y[j]

        y[i] = (b[i]-s)
    return y

def backwardSubs(U,y):
    cols, rows = U.shape

    x = np.zeros((cols, 1))
    for i in range(cols-1,-1,-1):

        s = 0
        for j in range(0,cols):
            s = s + U[i,j] * x[j]
        x[i] = (1/ U[i,i])*(y[i] - s)
    return x

In [5]:
b = np.array([[-23,54,2]])
b = b.T


y = forwardSubs(L,b,P)
print(backwardSubs(U,y))

[[-3.]
 [-0.]
 [ 4.]]


In [1]:
import numpy as np

A = np.array([[16,-4,-12],[-4,5,5],[-12,5,19]])
print(A)

# A = L*L.T

def cholesky(A):
    rows,cols = A.shape

    #Check if the matrix dimensions are equal
    if rows != cols:
        print('Matrix dimensions are not equal')

    #Create n x n zeros matrix
    L = np.zeros((rows,rows))

    for i in range(0,rows):
        #traverse only the left triangular matrix elements
        for j in range (0,i+1):
            if i == 0 and j ==0:
                L[0,0] = np.sqrt(A[0,0])

            else:
                if j == i:
                    s = 0
                    for k in range(0,i):
                        s = s + np.power(L[i,k],2)

                    L[i,i] = np.sqrt(A[i,i]-s)
                if j < i:
                    s = 0
                    for k in range (0,j):
                        s = s + L[i,k] *L[j,k]

                    L[i,j] = (1/ L[j,j]) *(A[i,j] -s)
    return L

print(cholesky(A))

[[ 16  -4 -12]
 [ -4   5   5]
 [-12   5  19]]
[[ 4.  0.  0.]
 [-1.  2.  0.]
 [-3.  1.  3.]]
