In [38]:
import numpy as np

# Excercise 1 task 1

A = np.array([[3, 7, -8], [8, 5, -5], [0, 3, -20]])
print(A)
print()

x = np.array([[33, 36, -5]])
x = x.T
print(x)
print()

aug_M = np.hstack((A, x, np.identity(3)))
print(aug_M)
print()

rows, cols = aug_M.shape

for i in range(rows):
    # make diagonal of A into 1
    aug_M[i,:] = aug_M[i,:]/aug_M[i,i]

    for k in range(rows):
        # substract all row elements by i  x i (1)
        if k != i:
            aug_M[k,:] = aug_M[k,:] -aug_M[k,i] * aug_M[i,:]
           
        
result = aug_M[:,3]
print('result is = ', result)

print('price of one sack of corn = ', result[0])
print('price of one whiskey = ', result[1])
print('price of one crew member per day = ', result[2])




[[  3   7  -8]
 [  8   5  -5]
 [  0   3 -20]]

[[33]
 [36]
 [-5]]

[[  3.   7.  -8.  33.   1.   0.   0.]
 [  8.   5.  -5.  36.   0.   1.   0.]
 [  0.   3. -20.  -5.   0.   0.   1.]]

result is =  [ 2.  5.  1.]
price of one sack of corn =  2.0
price of one whiskey =  5.0
price of one crew member per day =  1.0


# Gauss-Jordan elimination

Operations which do not change the solutions
1. Replace a row of A0 by a linear combination of itself and any other
row(s).
2. Interchange two rows of A0.
3. Interchange two columns of A
and corresponding rows of x.
 Basic G-J elimination uses only operation #1 but...


In [2]:
import numpy as np 

# Excercise 1 task 2 

A = np.array([[1, 2, 5, -3], [0, 0, -1, -1], [-1, -1, 0, 1], [3, -3, 2, -1]])
print(A)
print()

x = np.array([[-2, 6, 5, 1]])
x = x.T
print(x)
print()

aug_M = np.hstack((A, x, np.identity(4)))
print(aug_M)
print()




rows, cols = aug_M.shape

for i in range(rows):
    
    #index k = find the max value in i 
    #k = i + np argmax(np.absolute(aug_M[i:len(A), i]))
    #if k != i:
        #aug_M[[i,k]] = aug_M[[k,i]]
    if aug_M[i,i] == 0:
         aug_M[[i,i+1]] = aug_M[[i+1,i]]
    
    # make diagonal of A into 1
    aug_M[i,:] = aug_M[i,:]/aug_M[i,i]
    

    for k in range(rows):
        # substract all row elements by i  x i (1)
        if k != i:
            aug_M[k,:] = aug_M[k,:] -aug_M[k,i] * aug_M[i,:] 
            
        
result = aug_M[:,4]
print()
print('result is = ', result)




[[ 1  2  5 -3]
 [ 0  0 -1 -1]
 [-1 -1  0  1]
 [ 3 -3  2 -1]]

[[-2]
 [ 6]
 [ 5]
 [ 1]]

[[ 1.  2.  5. -3. -2.  1.  0.  0.  0.]
 [ 0.  0. -1. -1.  6.  0.  1.  0.  0.]
 [-1. -1.  0.  1.  5.  0.  0.  1.  0.]
 [ 3. -3.  2. -1.  1.  0.  0.  0.  1.]]


result is =  [-5.71428571 -4.66666667 -0.61904762 -5.38095238]
